import type { Series, SeriesStatus } from './types'

let _idCounter = 1
function id() { return String(_idCounter++) }

type R = [string, number|null, number|null, SeriesStatus, string|null, string, string|null, boolean]

const raw: R[] = [
  // title, season, episode, status, platform, notes, lastWatched, watchedWithPau
  // --- VIENDO AHORA ---
  ['Fubar',                        2, null, 'viendo',   'Netflix',      '',                                           '2023-06-25', false],
  ['Juego del Calamar',            4, null, 'viendo',   null,           '',                                           null,         false],
  ['Landman',                      1,   10, 'viendo',   'Paramount+',   '',                                           '2025-05-25', false],
  // --- RECIENTES 2025-2026 ---
  ['Stick',                        1, null, 'completa', 'Apple TV',     '',                                           null,         false],
  ['Mobland',                      1, null, 'completa', 'Paramount+',   'Inglesa, buenísima',                         null,         false],
  ['Alaska: La Última Frontera',   1, null, 'completa', 'Apple TV',     '',                                           '2025-11-17', false],
  ['La Bestia en Mí',              1, null, 'completa', 'Netflix',      '',                                           '2025-11-23', false],
  ['The White Lotus',              3, null, 'completa', 'HBO',          '',                                           '2025-08-31', false],
  ['Smoke',                        1, null, 'completa', 'Apple TV',     '',                                           '2025-08-15', false],
  ['Lioness',                      2, null, 'completa', 'Paramount+',   '',                                           null,         false],
  ['Adolescencia',              null, null, 'completa', null,           'Serie terminada',                            null,         false],
  ['Formula 1: Drive to Survive',  7, null, 'completa', 'Netflix',      '',                                           '2025-04-14', false],
  ['Yellowstone',                  5, null, 'completa', 'Paramount+',   'Serie terminada',                            '2025-02-01', false],
  ['The Last Narc',                1,    4, 'completa', 'Prime',        'Documental de Kiki Camarena',                null,         false],
  ['Zero Day',                     1, null, 'completa', 'Netflix',      'Robert de Niro, expresidente de EU',         '2025-02-01', false],
  ['Cross',                        1, null, 'completa', 'Prime',        '',                                           '2024-12-01', false],
  ['ZeroZeroZero',                 1, null, 'completa', 'Prime',        '',                                           '2025-01-01', false],
  ['Palomas Negras',               1,    6, 'completa', null,           '',                                           '2025-01-15', false],
  // --- 2024 ---
  ['El Paciente',               null, null, 'completa', 'Hulu',         'Psicólogo secuestrado por su paciente',      null,         true],
  ['Salvando a Jacob',          null, null, 'completa', null,           'Tailandesa',                                 null,         true],
  ['Se Presume Inocente',       null, null, 'completa', 'Apple TV',     '',                                           null,         true],
  ['El Señor de la Casa',       null, null, 'completa', 'Apple TV',     '',                                           '2024-07-16', false],
  ['Domina',                       2, null, 'completa', null,           'De Livia, la romana',                        '2024-06-29', false],
  ['Todo un Hombre',            null, null, 'completa', null,           'Empresario al borde de bancarrota',          '2024-05-05', false],
  ['El Problema de los 3 Cuerpos', 1, null, 'completa', 'Netflix',      'Ciencia ficción, extraterrestres',           '2024-05-01', false],
  ['Mano de Hierro',            null, null, 'completa', null,           'Española, mafia en Puerto de Barcelona',     '2024-05-01', false],
  ['No Estás Sola',             null, null, 'completa', 'Netflix',      'Violación en Pamplona',                      '2024-05-01', false],
  ['Griselda',                  null, null, 'completa', 'Netflix',      'Narca colombiana',                           '2024-05-01', false],
  ['Maleantes',                    1, null, 'completa', 'Netflix',      '',                                           '2024-04-01', false],
  ['Caballeros',                   1, null, 'completa', null,           '',                                           '2024-04-01', false],
  ['Masters of the Air',           1, null, 'completa', 'Apple TV',     '',                                           '2024-04-01', false],
  ['Quédate Cerca',             null, null, 'completa', 'Netflix',      'Inglesa',                                    '2024-03-29', false],
  ['Beckham',                      1, null, 'completa', 'Netflix',      '',                                           '2024-12-03', false],
  ['The Pacific',               null, null, 'completa', 'HBO',          'Guerra del Pacífico, EU vs Japón, 2a GM',    '2024-12-03', false],
  ['The Crown',                    6, null, 'completa', 'Netflix',      '',                                           '2023-12-27', true],
  // --- 2023 ---
  ['Valley of Tears',           null, null, 'completa', 'HBO',          'Guerra Siria-Israel',                        '2023-12-27', false],
  ['Ecos',                      null, null, 'completa', null,           'Hermanas que intercambian vidas',            '2023-08-07', false],
  ['Secuestro Aéreo',              1, null, 'completa', 'Apple TV',     '',                                           null,         false],
  ['Succession',                   4, null, 'completa', 'HBO',          '',                                           '2023-07-01', false],
  ['La Diplomática',               1, null, 'completa', 'Netflix',      '',                                           null,         false],
  ['Agente Nocturno',              1, null, 'completa', 'Netflix',      '',                                           '2023-03-30', false],
  ['Traición',                  null, null, 'completa', 'Netflix',      '',                                           '2023-03-15', false],
  ['El Novato',                    1, null, 'completa', 'Netflix',      '',                                           '2023-03-01', false],
  ['YOU',                          4, null, 'completa', 'Netflix',      'Psicópata que mata a sus novias',            '2023-03-01', true],
  ['Fauda',                        4, null, 'completa', 'Netflix',      '',                                           '2023-03-01', false],
  ['Beckham',                      1, null, 'completa', 'Netflix',      '',                                           '2023-01-01', false],
  // --- 2022 ---
  ['La Línea: Sombra del Narco',null, null, 'completa', 'Apple TV',     '',                                           '2023-01-01', false],
  ['Sons of Anarchy',              7, null, 'completa', 'Prime',        '',                                           '2022-12-01', false],
  ['Blackbird',                    1, null, 'completa', 'Apple TV',     '',                                           '2022-09-11', false],
  ['Dopesick',                     1, null, 'completa', 'Star+',        '',                                           '2022-09-04', true],
  ['The Thing About Pam',          1, null, 'completa', 'Star+',        '',                                           '2022-08-01', false],
  ['Zodiaco (Documental)',          1, null, 'completa', null,           'Documental del hijo del asesino',            '2022-08-01', true],
  ['Capitani',                     2, null, 'completa', null,           'Luxemburgo, policía resuelve caso',          '2022-08-15', false],
  ['Perfume',                      1, null, 'completa', null,           '',                                           '2022-08-15', true],
  ['The Ozarks',                   4, null, 'completa', 'Netflix',      '',                                           '2022-06-06', false],
  ['Una Madre Perfecta',           1, null, 'completa', 'Netflix',      'Francesa',                                   '2022-06-05', true],
  ['Vikings: Valhalla',            1, null, 'completa', 'Netflix',      '',                                           null,         false],
  // --- 2021 ---
  ['Narcos: México',               3, null, 'completa', 'Netflix',      '',                                           '2021-11-15', false],
  ['Atracadores',                  1, null, 'completa', 'Netflix',      'Francesa, robos, drogas, secuestros',        '2021-10-03', false],
  ['Billions',                     5, null, 'completa', null,           '',                                           '2021-10-02', false],
  ['Ballers',                      3,    5, 'completa', null,           'Asesores financieros de futbol americano',   '2021-09-15', false],
  ['Hit List',                     1, null, 'completa', 'HBO',          '',                                           '2021-09-15', false],
  ['The Flight Attendant',         1, null, 'completa', 'HBO',          '',                                           '2021-09-15', false],
  ['Sharp Objects',                1, null, 'completa', 'HBO',          'Mamá que enferma a sus hijas',               '2021-09-15', false],
  ['Casa de Papel',                5, null, 'completa', 'Netflix',      '',                                           '2021-09-12', true],
  ['In the Line of Duty',          1, null, 'completa', null,           'Policía inglesa',                            '2021-07-16', false],
  ['El Método Kominsky',           3, null, 'completa', 'Netflix',      'Michael Douglas',                            '2021-06-01', false],
  ['¿Quién Mató a Sara?',          1, null, 'completa', 'Netflix',      'Mexicana',                                   '2021-05-25', true],
  ['Shtisel',                      3, null, 'completa', 'Netflix',      'Judíos ultra ortodoxos',                     '2021-04-25', false],
  ['Detrás de Sus Ojos',           1, null, 'completa', 'Netflix',      'Mujer con poderes que sale de su cuerpo',    '2021-03-15', false],
  ['Spotless',                     1, null, 'completa', null,           'Francesa-inglesa, los que limpian asesinatos','2021-01-30', false],
  ['No te Metas con los Gatos',    1, null, 'completa', 'Netflix',      'Mini documental',                            '2021-01-24', false],
  ['Lupin',                        1, null, 'completa', 'Netflix',      '',                                           '2021-01-01', false],
  // --- 2020 ---
  ['Bárbaros',                     1, null, 'completa', 'Netflix',      '',                                           '2020-12-21', false],
  ['The Undoing',                  1, null, 'completa', 'HBO',          'Nicole Kidman y Hugh Grant',                 '2020-12-16', true],
  ['Suburra',                      3, null, 'completa', 'Netflix',      '',                                           '2020-11-06', false],
  ['Paranoid',                  null, null, 'completa', null,           'Inglesa',                                    '2020-11-01', false],
  ['McMafia',                      1, null, 'completa', 'Prime',        '',                                           '2020-11-01', false],
  ['Tehran',                       1, null, 'completa', 'Apple TV',     '',                                           '2020-10-30', false],
  ['Mother Father Son',            1, null, 'completa', 'Prime',        '',                                           '2020-10-30', false],
  ['Bajo Sospecha',                2, null, 'completa', null,           '',                                           '2020-10-18', false],
  ['Reckoning',                    1, null, 'completa', null,           '',                                           '2020-09-02', true],
  ['Spartacus',                    4, null, 'completa', null,           '',                                           '2020-08-14', false],
  ['El Espía',                     1, null, 'completa', 'Netflix',      '',                                           '2020-08-01', false],
  ['Marcella',                     3, null, 'completa', 'Netflix',      '',                                           '2020-08-01', false],
  ['The Sinner',                   3, null, 'completa', 'Netflix',      '',                                           '2020-07-01', false],
  ['White Lines',                  1, null, 'completa', 'Netflix',      'Chavos que venden drogas en Ibiza',          '2020-07-01', false],
  ['Los Asesinatos de Valhalla',   1, null, 'completa', null,           '',                                           '2020-05-01', false],
  ['Califato',                     1, null, 'completa', null,           '',                                           '2020-04-01', false],
  ['Vikings',                      6, null, 'completa', null,           '',                                           null,         false],
  ['Dilema (What If)',             1, null, 'completa', null,           '',                                           '2020-03-15', false],
  ['El Diablo de al Lado',         1, null, 'completa', null,           '',                                           '2020-01-29', false],
  ['El Caso de Aaron Hernandez',   1, null, 'completa', 'Netflix',      '',                                           '2020-01-28', false],
  ['Los Últimos Zares',            1, null, 'completa', 'Netflix',      '',                                           '2020-01-24', false],
  // --- 2019 ---
  ['Nobel',                        1, null, 'completa', null,           '',                                           '2019-10-06', false],
  ['La Catedral del Mal',          1, null, 'completa', null,           '',                                           '2019-10-01', false],
  ['La Víctima Número 8',          1, null, 'completa', null,           '',                                           '2019-08-23', false],
  ['Designated Survivor',          3, null, 'completa', 'Netflix',      '',                                           '2019-07-06', false],
  ['Bad Blood',                    2, null, 'completa', null,           '',                                           '2019-07-01', false],
  ['Perros de Berlín',             1, null, 'completa', null,           '',                                           '2019-07-01', false],
  ['House of Cards',               6, null, 'completa', 'Netflix',      '',                                           '2019-06-01', false],
  ['La Trève (Belga)',             2, null, 'completa', null,           '',                                           '2019-06-01', false],
  ['Trapped (Islandesa)',          1, null, 'completa', null,           '',                                           '2019-06-01', false],
  ['Vivir sin Permiso',            1, null, 'completa', 'Netflix',      '',                                           '2019-05-05', false],
  ['Crímenes Americanos: Versace', 1, null, 'completa', 'FX',           '',                                           '2019-05-01', false],
  ['The Night Manager',            1, null, 'completa', 'Prime',        '',                                           '2019-04-23', false],
  ['Intersection',                 3, null, 'completa', null,           '',                                           '2019-04-01', false],
  ['Suits',                        9, null, 'completa', 'Netflix',      '',                                           '2019-04-01', false],
  // --- 2018 ---
  ['The Bodyguard',                1, null, 'completa', 'Netflix',      '',                                           '2018-10-01', false],
  ['Crímenes Americanos: OJ Simpson',1, null,'completa','FX',           '',                                           '2018-06-01', false],
  ['Collateral',                   1, null, 'completa', null,           '',                                           '2018-04-12', false],
  ['Manhunt: Unabomber',           1, null, 'completa', null,           '',                                           '2018-03-01', false],
  ['Marsella',                     2, null, 'completa', null,           '',                                           '2018-02-15', false],
  ['The Following',                3, null, 'completa', null,           '',                                           '2018-01-01', true],
  // --- 2017 ---
  ['Narcos',                       3, null, 'completa', 'Netflix',      '',                                           '2017-11-01', false],
  ['The Fall',                     3, null, 'completa', 'Netflix',      '',                                           '2017-02-01', false],
  // --- 2016 ---
  ['ZOO',                          1, null, 'completa', null,           '',                                           '2016-12-03', false],
  ['Homeland',                     5, null, 'completa', null,           '',                                           '2016-08-03', false],
  // --- CLÁSICOS / ANTES ---
  ['Sons of Anarchy',              7, null, 'completa', 'Prime',        '',                                           '2022-12-01', false],
  ['Better Call Saul',             6, null, 'completa', 'Netflix',      '',                                           '2022-01-01', false],
  ['Breaking Bad',                 5, null, 'completa', 'Netflix',      '',                                           '2014-03-03', false],
  ['Borgias',                      3, null, 'completa', null,           '',                                           '2014-10-13', false],
  ['Game of Thrones',              8, null, 'completa', 'HBO',          '',                                           null,         false],
  ['Lillyhammer',                  1, null, 'completa', 'Netflix',      '',                                           '2012-01-01', false],
  // --- PENDIENTES ---
  ['Cazadores',                 null, null, 'pendiente', null,          'De judíos, muy buena',                       null,         false],
  ['Angela',                    null, null, 'pendiente', null,          '',                                           null,         false],
  ['Indomable',                 null, null, 'pendiente', null,          '',                                           null,         false],
  ['Sirenas',                   null, null, 'pendiente', 'Netflix',     '',                                           null,         false],
  ['The Old Man',               null, null, 'pendiente', 'FX',          '',                                           null,         false],
  ['El Legado',                 null, null, 'pendiente', null,          '',                                           null,         false],
  ['Ciudad en Llamas',          null, null, 'pendiente', 'Apple TV',    '',                                           null,         false],
  ['Swimming with Sharks',      null, null, 'pendiente', 'Prime',       '',                                           null,         false],
  ['El Vigilante',              null, null, 'pendiente', null,          '',                                           null,         false],
  ['El Turista',                null, null, 'pendiente', null,          'Australiana',                                null,         false],
  ['Engaños',                   null, null, 'pendiente', null,          'Inglesa',                                    null,         false],
  ['Safe',                      null, null, 'pendiente', null,          'Inglesa',                                    null,         false],
  ['Una Familia Normal',        null, null, 'pendiente', null,          'Sueca',                                      null,         false],
  ['Gomorra',                      3,    8, 'pausada',   null,          '',                                           '2019-08-01', false],
  ['Blindspot',                    3,    4, 'pausada',   null,          '',                                           '2020-04-01', false],
  ['The Last Kingdom',             2,    4, 'pausada',   null,          '',                                           '2019-01-01', false],
  ['Entrevías',                 null, null, 'completa',  'Netflix',     'Serie terminada',                            null,         false],
  ['Obsesión',                  null, null, 'completa',  'Netflix',     '',                                           null,         false],
  ['El Diablo Está en Ohio',    null, null, 'completa',  'Netflix',     '',                                           null,         false],
  ['Frente Costero',               1, null, 'completa',  null,          '',                                           null,         false],
]

// Remove duplicate Beckham entry
const seen = new Set<string>()
const deduped = raw.filter(r => {
  const key = r[0].toLowerCase()
  if (seen.has(key)) return false
  seen.add(key)
  return true
})

export const initialData: Series[] = deduped.map((r) => ({
  id: id(),
  title: r[0],
  currentSeason: r[1],
  currentEpisode: r[2],
  status: r[3],
  platform: r[4],
  notes: r[5],
  lastWatched: r[6],
  watchedWithPau: r[7],
}))
